package com.naveenans.olabatteryalert;
import android.app.*; import android.appwidget.*; import android.content.*; import android.content.pm.PackageManager; import android.graphics.Color; import android.os.*; import android.provider.Settings; import android.widget.*; import java.text.DateFormat; import java.util.Date;
public class MainActivity extends Activity {
 private static final int HOST_ID=41041,PICK=701,CONFIG=702; private BatteryWidgetHost host; private LinearLayout box; private TextView status,limitText; private SeekBar limit;
 @Override public void onCreate(Bundle b){super.onCreate(b); AlertEngine.channels(this); if(Build.VERSION.SDK_INT>=33&&checkSelfPermission("android.permission.POST_NOTIFICATIONS")!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{"android.permission.POST_NOTIFICATIONS"},900); host=new BatteryWidgetHost(this,HOST_ID); build(); showWidget(); refresh();}
 @Override protected void onStart(){super.onStart();host.startListening();} @Override protected void onStop(){host.stopListening();super.onStop();}
 private TextView t(String s,int sp){TextView v=new TextView(this);v.setText(s);v.setTextSize(sp);v.setTextColor(Color.WHITE);v.setPadding(0,10,0,10);return v;} private Button b(String s){Button x=new Button(this);x.setText(s);return x;}
 private void build(){ScrollView sv=new ScrollView(this);sv.setBackgroundColor(Color.rgb(16,20,24));LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(36,42,36,48);sv.addView(r);TextView h=t("Ola Battery Alert",28);h.setTypeface(null,1);r.addView(h);r.addView(t("Host the Ola Electric widget here, read its displayed scooter battery %, and alert when your selected charging limit is reached.",15));limitText=t("",20);r.addView(limitText);limit=new SeekBar(this);limit.setMax(40);int saved=getSharedPreferences("prefs",0).getInt("limit",80);limit.setProgress(saved-60);r.addView(limit);limit.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onProgressChanged(SeekBar s,int p,boolean f){int x=60+p;limitText.setText("Charge alert: "+x+"%");getSharedPreferences("prefs",0).edit().putInt("limit",x).apply();}public void onStartTrackingTouch(SeekBar s){}public void onStopTrackingTouch(SeekBar s){}});box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(0,16,0,16);r.addView(box);Button pick=b("Select / Change Ola Widget");pick.setOnClickListener(v->pick());r.addView(pick);Button n=b("Enable Ola Notification Fallback");n.setOnClickListener(v->startActivity(new Intent(Settings.ACTION_NOTIFICATION_LISTENER_SETTINGS)));r.addView(n);Button m=b("Start Background Monitor");m.setOnClickListener(v->{getSharedPreferences("prefs",0).edit().putBoolean("monitor",true).apply();try{startForegroundService(new Intent(this,WidgetMonitorService.class));Toast.makeText(this,"Monitor started",Toast.LENGTH_SHORT).show();}catch(Exception e){Toast.makeText(this,e.getMessage(),Toast.LENGTH_LONG).show();}});r.addView(m);Button test=b("Test Limit Alert");test.setOnClickListener(v->{int l=getSharedPreferences("prefs",0).getInt("limit",80);AlertEngine.send(this,l,l,"test");});r.addView(test);status=t("",14);r.addView(status);setContentView(sv);}
 private void pick(){int id=host.allocateAppWidgetId();Intent i=new Intent(AppWidgetManager.ACTION_APPWIDGET_PICK);i.putExtra(AppWidgetManager.EXTRA_APPWIDGET_ID,id);startActivityForResult(i,PICK);}
 @Override protected void onActivityResult(int req,int res,Intent data){super.onActivityResult(req,res,data);if(res!=RESULT_OK)return;int id=data.getIntExtra(AppWidgetManager.EXTRA_APPWIDGET_ID,AppWidgetManager.INVALID_APPWIDGET_ID);if(req==PICK){AppWidgetProviderInfo info=AppWidgetManager.getInstance(this).getAppWidgetInfo(id);if(info!=null&&info.configure!=null){Intent c=new Intent(AppWidgetManager.ACTION_APPWIDGET_CONFIGURE);c.setComponent(info.configure);c.putExtra(AppWidgetManager.EXTRA_APPWIDGET_ID,id);startActivityForResult(c,CONFIG);}else save(id);}else if(req==CONFIG)save(id);}
 private void save(int id){AppWidgetProviderInfo info=AppWidgetManager.getInstance(this).getAppWidgetInfo(id);String pkg=info!=null&&info.provider!=null?info.provider.getPackageName():"";getSharedPreferences("prefs",0).edit().putInt("widget_id",id).putString("widget_pkg",pkg).apply();showWidget();refresh();}
 private void showWidget(){box.removeAllViews();int id=getSharedPreferences("prefs",0).getInt("widget_id",AppWidgetManager.INVALID_APPWIDGET_ID);if(id==AppWidgetManager.INVALID_APPWIDGET_ID){box.addView(t("No Ola widget selected yet.",16));return;}AppWidgetProviderInfo info=AppWidgetManager.getInstance(this).getAppWidgetInfo(id);if(info==null){box.addView(t("Widget unavailable. Select it again.",16));return;}BatteryWidgetHostView v=(BatteryWidgetHostView)host.createView(this,id,info);v.setListener(p->{if(p!=null){AlertEngine.process(this,p,"Ola widget");refresh();}});box.addView(v,new LinearLayout.LayoutParams(-1,Math.max(180,info.minHeight)));v.postDelayed(()->{Integer p=BatteryParser.fromView(v);if(p!=null){AlertEngine.process(this,p,"Ola widget");refresh();}},800);}
 private void refresh(){android.content.SharedPreferences p=getSharedPreferences("prefs",0);int pct=p.getInt("last_pct",-1);long tm=p.getLong("last_update",0);status.setText("Last battery: "+(pct<0?"—":pct+"%")+"\nLast update: "+(tm==0?"Never":DateFormat.getDateTimeInstance().format(new Date(tm)))+"\nSource: "+p.getString("last_source","none")+"\nWidget package: "+p.getString("widget_pkg","not selected")+"\n\nUse the Ola widget that visibly shows scooter battery percentage. Keep the monitor enabled while charging.");}
}
